kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true  # Disables Kindnet
  podSubnet: "192.168.0.0/16"  # Ensure compatibility with Calico
nodes:
- role: control-plane
- role: worker

