apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: custom-nginx-daemonset  
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: new-cluster1-worker2  
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
