apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
  - name: init-container
    image: alpine:latest
    command: ['sh', '-c', 'echo "Initializing the app..." > /data/init.txt; sleep 5']
    volumeMounts:
      - name: shared-data
        mountPath: /data
  containers:
  - name: main-container
    image: alpine:latest
    command: ['sh', '-c', 'while true; do echo "Main container is running $(date)"; sleep 1; done']
    volumeMounts:
      - name: shared-data
        mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}
