apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo-app
    environment: dev
    team: devops
  annotations:
    description: "This is a demo pod for labels and annotations"
    build: "v1.0"
spec:
  containers:
  - name: nginx-container
    image: nginx
