apiVersion: v1
kind: Pod
metadata:
  name: multi-label-selector-pod
spec:
  nodeSelector:
    disktype: ssd
    region: us-west
  containers:
  - name: example-container
    image: nginx
    command: ["sh", "-c", "echo Hello from us-west SSD node!"]
