apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpassword
    startupProbe:
      exec:
        command:
          - "mysql"
          - "-uroot"
          - "-prootpassword"
          - "-e"
          - "SELECT 1;"
      initialDelaySeconds: 60  # Allow MySQL enough time to start
      periodSeconds: 5
      failureThreshold: 10
      timeoutSeconds: 3
    ports:
    - containerPort: 3306
