apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/2 * * * *"  # Runs every 2 minutes
  jobTemplate:
    spec:
      completions: 5        # Each Job requires 5 successful pods
      parallelism: 2        # Run 2 pods at a time
      backoffLimit: 3       # Retry a failed pod 3 times
      activeDeadlineSeconds: 60  # Each job must complete in 60 seconds
      template:
        spec:
          containers:
          - name: worker
            image: busybox
            command: ["sh", "-c", "echo Running task; sleep 10"]
          restartPolicy: Never
